<option value="note">Choose a recipient</option>
<option value="brittanykelley@perrysfurniture.com">Brittany</option>
<option value="kimberlyperry@perrysfurniture.com">Kim</option>
<option value="cynthiawhite@perrysfurniture.com">Cindy</option>
<option value="annaleighfultz@perrysfurniture.com">Anna Leigh</option>
<option value="jillluks@perrysfurniture.com">Jill</option>
<option value="jenniferrockey@perrysfurniture.com">Jenn</option>
<option value="lauriewheeler@perrysfurniture.com">Laurie</option>
<option value="jeremydanforth@perrysfurniture.com">Jeremy</option>
<option value="warehouse@perrysfurniture.com">Warehouse</option>
<option value="gardinermoody@perrysfurniture.com">Tech Support</option>